integrations:
  prometheus_remote_write:
    - basic_auth:
        password: eyJrIjoiOTI2M2FjNzBiYzE5ZWYwZGIyZTQ5NzIzZGNiZWI4Yzk4YTBhMGYwMiIsIm4iOiJkaWdpdGFsZW1pbC1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJpZCI6NTk2NjUxfQ==
        username: 319844
      url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
logs:
  configs:
    - clients:
        - basic_auth:
            password: eyJrIjoiOTI2M2FjNzBiYzE5ZWYwZGIyZTQ5NzIzZGNiZWI4Yzk4YTBhMGYwMiIsIm4iOiJkaWdpdGFsZW1pbC1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJpZCI6NTk2NjUxfQ==
            username: 158892
          url: https://logs-prod-eu-west-0.grafana.net/api/prom/push
      name: integrations
      positions:
        filename: /tmp/positions.yaml
      target_config:
        sync_period: 10s
metrics:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: eyJrIjoiOTI2M2FjNzBiYzE5ZWYwZGIyZTQ5NzIzZGNiZWI4Yzk4YTBhMGYwMiIsIm4iOiJkaWdpdGFsZW1pbC1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJpZCI6NTk2NjUxfQ==
            username: 319844
          url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
      scrape_configs:
        - job_name: integrations/nodejs
          static_configs:
            - targets: ['thegym.theblackapp.de']
  global:
    scrape_interval: 10s
  wal_directory: /tmp/grafana-agent-wal
server:
  http_listen_port: 12345
