integrations:
  agent:
    enabled: true
  prometheus_remote_write:
    - basic_auth:
        password: eyJrIjoiOTI2M2FjNzBiYzE5ZWYwZGIyZTQ5NzIzZGNiZWI4Yzk4YTBhMGYwMiIsIm4iOiJkaWdpdGFsZW1pbC1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJpZCI6NTk2NjUxfQ==
        username: 319844
      url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
logs:
  configs:
    - clients:
        - basic_auth:
            password: eyJrIjoiYzE5OTViMjJlZmYxZWVkZTMwZjBkOWIzYjQzNTcyNjU1YmZhZWY0MyIsIm4iOiJ0aGVneW0tbG9ncyIsImlkIjo1OTY2NTF9
            username: 158892
          url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
      name: integrations
      positions:
        filename: /tmp/positions.yaml
      target_config:
        sync_period: 10s
      scrape_configs:
        - job_name: thegym/logs
          static_configs:
            - labels:
                __path__: /opt/app/logs/microservice-sqlui/*.log
                app: thegym
                service: sqlui
              targets:
                - localhost
            - labels:
                __path__: /opt/app/logs/microservice-pmmlevaluator/*.log
                app: thegym
                service: pmmlevaluator
              targets:
                - localhost
            - labels:
                __path__: /opt/app/logs/microservice-messagepersister/*.log
                app: thegym
                service: messagepersister
              targets:
                - localhost
            - labels:
                __path__: /opt/app/logs/microservice-frontend/*.log
                app: thegym
                service: frontend
              targets:
                - localhost
            - labels:
                __path__: /opt/app/logs/microservice-messagelistener/*.log
                app: thegym
                service: messagelistener
              targets:
                - localhost
            - labels:
                __path__: /opt/app/logs/microservice-messagetransformer/*.log
                app: thegym
                service: messagetransformer
              targets:
                - localhost
            - labels:
                __path__: /opt/app/logs/microservice-messagevalidator/*.log
                app: thegym
                service: messagevalidator
              targets:
                - localhost
            - labels:
                __path__: /opt/app/logs/microservice-messagelogger/*.txt
                app: thegym
                service: messagelogger
              targets:
                - localhost
            - labels:
                __path__: /opt/app/logs/microservice-messageduplicator/*.log
                app: thegym
                service: messageduplicator
              targets:
                - localhost
            - labels:
                __path__: /cockroach-data/logs/cockroach.*root*log
                app: thegym
                service: cockroachdb
              targets:
                - localhost

metrics:
  configs:
    - name: integrations
      remote_write:
        - basic_auth:
            password: eyJrIjoiOTI2M2FjNzBiYzE5ZWYwZGIyZTQ5NzIzZGNiZWI4Yzk4YTBhMGYwMiIsIm4iOiJkaWdpdGFsZW1pbC1lYXN5c3RhcnQtcHJvbS1wdWJsaXNoZXIiLCJpZCI6NTk2NjUxfQ==
            username: 319844
          url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
      scrape_configs:
        - job_name: integrations/nodejs
          static_configs:
            - targets: ['thegym.theblackapp.de']
            - labels:
                service: "frontend"
        - job_name: messagetransformer
          static_configs:
            - targets: ['127.0.0.1:3032']
            - labels:
                app: thegym
                service: "messagetransformer"      
        - job_name: messagevalidator
          static_configs:
            - targets: ['127.0.0.1:3033']
            - labels:
                app: thegym
                service: "messagevalidator"
        - job_name: messagelistener
          static_configs:
            - targets: ['127.0.0.1:3034']
            - labels:
                app: thegym
                service: "messagelistener"        
        - job_name: messagepersister
          static_configs:
            - targets: ['127.0.0.1:3038']
            - labels:
                app: thegym
                service: "messagepersister"        
        - job_name: messagelogger
          static_configs:
            - targets: ['127.0.0.1:3036']
            - labels:
                app: thegym
                service: "messagelogger"
        - job_name: pmmlevaluator
          metrics_path: /actuator/prometheus
          static_configs:
            - targets: ['127.0.0.1:8080']
            - labels:
                app: thegym
                service: "pmmlevaluator"
        - job_name: sqlui
          metrics_path: /sql/actuator/prometheus
          static_configs:
            - targets: ['127.0.0.1:8081']
            - labels:
                app: thegym
                service: "sqlui"
        - job_name: integrations/python-django
          metrics_path: /metrics
          static_configs:
            - targets: ['127.0.0.1:3037']
            - labels:
                app: thegym
                service: "messageduplicator"
        - job_name: integrations/cockroachdb
          metrics_path: /_status/vars
          static_configs:
            - targets: ['127.0.0.1:8088']
            - labels:
                app: thegym
                service:  "cockroachdb"
  global:
    scrape_interval: 10s
  wal_directory: /tmp/grafana-agent-wal
traces:
  configs:
  - name: default
    remote_write:
      - endpoint: tempo-eu-west-0.grafana.net:443
        basic_auth:
          username: 155402
          password: eyJrIjoiODBjYWE4MGM2MDk4NmY0NWQ1NDU5ZGZiMDc2ZjVmYzg1OTYxNjAzZCIsIm4iOiJ0aGVneW0tdHJhY2VzIiwiaWQiOjU5NjY1MX0=
    receivers:
      otlp:
        protocols:
          grpc:
server:
  http_listen_port: 12345
